sudo: false
dist: trusty
addons:
  mariadb: "10.0"
env:
  global:
  - DATABASES_MYSQL_NAME=gin_project
  - DATABASES_MYSQL_USER=www
  - DATABASES_MYSQL_PASSWORD=123456
language: go
go:
  - tip
before_install:
  - sudo apt-get install -y libmariadbclient-dev
  - mysql -e "CREATE USER '${DATABASES_MYSQL_USER}'@'%' IDENTIFIED BY '${DATABASES_MYSQL_PASSWORD}';"
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO '${DATABASES_MYSQL_USER}'@'%' IDENTIFIED BY '${DATABASES_MYSQL_PASSWORD}' WITH GRANT OPTION;"
  - mysql -e "FLUSH PRIVILEGES;"
  - mysql -e "CREATE DATABASE IF NOT EXISTS ${DATABASES_MYSQL_NAME};"
# command to install dependencies
install:
  - go get -u github.com/kardianos/govendor
  - govendor sync
  - go get -u golang.org/x/tools/cmd/cover
  - go get -u github.com/mattn/goveralls
before_script:
  - mysql -e "SOURCE dbs/schema/mysql.sql; SOURCE dbs/data/mysql.sql; SHOW databases; SHOW tables;"
# command to run tests
script:
  - source env_test.sh
  - go test github.com/zhanghe06/gin_project/tests -coverprofile=.coverage
after_script:
  - mysql -e "DROP DATABASE IF EXISTS ${DATABASES_MYSQL_NAME};"
after_success:
  - goveralls -coverprofile=.coverage
